<script lang="ts">
	import { formatShortDate } from '$lib/utils/format'
	import type { PageData } from './$types'

	let { data }: { data: PageData } = $props()

	const reviewStatusClass = (status: string) =>
		status === 'COMPLETED' || status === 'ACKNOWLEDGED'
			? 'bg-green-500/15 text-green-400'
			: status === 'PENDING'
				? 'bg-yellow-500/15 text-yellow-400'
				: status === 'SCORED' || status === 'SIGNING'
					? 'bg-purple-500/15 text-purple-400'
					: 'bg-blue-500/15 text-blue-400'
</script>

<svelte:head>
	<title>Performance — Veent HRIS</title>
</svelte:head>

<div class="space-y-6">
	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-bold tracking-tight">Performance</h1>
	</div>

	<!-- #178 readiness note. Informational, never a gate: it disables nothing and blocks no
	     action. The count is 0 for anyone without ADMINISTER_HR_ORGWIDE (see the load), so the
	     capability check is the server's and `> 0` is the whole client-side condition. -->
	{#if data.templateBackfill > 0}
		<p class="rounded-md border border-yellow-500/30 bg-yellow-500/10 px-3 py-2 text-sm">
			{data.templateBackfill} active
			{data.templateBackfill === 1 ? 'employee has' : 'employees have'} no assigned template. This is
			a readiness note, not a blocker.
		</p>
	{/if}

	<!-- Review Cycles (HR) — read-only. #178: cycles are generated by the nightly cron, so there
	     is no create form and no hand-run status transition; this is the record of what it made. -->
	{#if data.isAdmin && data.cycles.length}
		<section class="space-y-3">
			<h2 class="text-lg font-semibold">Review Cycles</h2>
			<div class="overflow-x-auto rounded-lg border">
				<table class="w-full text-sm">
					<thead class="border-b bg-muted/50">
						<tr>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Period</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
						</tr>
					</thead>
					<tbody class="divide-y">
						{#each data.cycles as c (c.id)}
							<tr class="hover:bg-muted/30">
								<td class="px-4 py-3 font-medium">{c.name}</td>
								<td class="px-4 py-3 text-muted-foreground"
									>{formatShortDate(c.startDate)} – {formatShortDate(c.endDate)}</td
								>
								<td class="px-4 py-3"
									><span
										class="rounded-full px-2 py-0.5 text-xs font-medium {reviewStatusClass(
											c.status
										)}">{c.status}</span
									></td
								>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</section>
	{/if}

	<!-- My Reviews -->
	<section class="space-y-3">
		<h2 class="text-lg font-semibold">My Reviews</h2>
		<div class="overflow-x-auto rounded-lg border">
			<table class="w-full text-sm">
				<thead class="border-b bg-muted/50">
					<tr>
						<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
						<th class="px-4 py-3 text-left font-medium text-muted-foreground">Reviewer</th>
						<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
					</tr>
				</thead>
				<tbody class="divide-y">
					{#each data.myReviews as review (review.id)}
						<tr class="hover:bg-muted/30">
							<td class="px-4 py-3"
								><a
									href="/performance/reviews/{review.id}"
									class="font-medium text-primary hover:underline">{review.cycle.name}</a
								></td
							>
							<td class="px-4 py-3 text-muted-foreground">
								{review.reviewer.lastName}, {review.reviewer.firstName}
							</td>
							<td class="px-4 py-3">
								<span
									class="rounded-full px-2 py-0.5 text-xs font-medium {reviewStatusClass(
										review.status
									)}"
								>
									{review.status}
								</span>
							</td>
						</tr>
					{:else}
						<tr>
							<td colspan="3" class="px-4 py-8 text-center text-muted-foreground">No reviews</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</section>

	<!-- Reviews to Complete (reviewer) -->
	{#if data.reviewsToGive.length}
		<section class="space-y-3">
			<h2 class="text-lg font-semibold">Reviews to Complete</h2>
			<div class="overflow-x-auto rounded-lg border">
				<table class="w-full text-sm">
					<thead class="border-b bg-muted/50">
						<tr>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Employee</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Cycle</th>
							<th class="px-4 py-3 text-left font-medium text-muted-foreground">Status</th>
						</tr>
					</thead>
					<tbody class="divide-y">
						{#each data.reviewsToGive as review (review.id)}
							<tr class="hover:bg-muted/30">
								<td class="px-4 py-3"
									><a
										href="/performance/reviews/{review.id}"
										class="font-medium text-primary hover:underline"
										>{review.employee.lastName}, {review.employee.firstName}</a
									></td
								>
								<td class="px-4 py-3 text-muted-foreground">{review.cycle.name}</td>
								<td class="px-4 py-3">
									<span
										class="rounded-full px-2 py-0.5 text-xs font-medium {reviewStatusClass(
											review.status
										)}"
									>
										{review.status}
									</span>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</section>
	{/if}
</div>
